yolla/category/urls.py
from django.urls import path, re_path
from . import views as v

app_name = 'category'

urlpatterns = [
    path('list', v.List.as_view(), name='list'),  # superuser only
    path('new', v.New.as_view(), name='new'),  # superuser only
    re_path(r'^update/(?P<pk>\d+)$', v.Update.as_view(), name='update'),  # superuser only

    re_path(r'^(?P<slug>[\w-]+)$', v.container, name='container'),  # public
]

yolla/opinion/urls.py
from django.urls import path, re_path
from . import views as v, views_reply as reply, views_attachment as attachment, views_read as read

app_name = 'opinion'

urlpatterns = [
    path('list', v.List.as_view(), name='list'),  # staff
    re_path(r'^new/(?P<topic_slug>[\w-]+)$', v.New.as_view(), name='new'),  # superuser only
    re_path(r'^update/(?P<pk>\d+)$', v.Update.as_view(), name='update'),  # staff
    re_path(r'^read/(?P<pk>\d+)$', v.read, name='read'),  # staff

    re_path(r'^reply_to_(?P<reply_to_opinion_pk>\d+)$', reply.Reply.as_view(), name='reply'),  # participant
    re_path(r'^edit_(?P<pk>\d+)$', reply.Edit.as_view(), name='edit'),  # participant
    re_path(r'^cancel_(?P<pk>\d+)$', reply.cancel, name='cancel'),  # participant

    re_path(r'^attach_documents_(?P<opinion_pk>\d+)$', attachment.attach_documents, name='attach_documents'),  # participant
    re_path(r'^delete_document_(?P<attachment_pk>\d+)$', attachment.delete_document, name='delete_document'),  # participant
    re_path(r'^documents_(?P<opinion_pk>\d+)$', attachment.zip_documents, name='zip_documents'),  # public

    path('replies', read.Replies.as_view(), name='replies'),  # participant
    re_path(r'^your_reply_(?P<pk>\d+)$', read.your_reply, name='your_reply'),  # participant
    re_path(r'^(?P<topic_slug>[\w-]+)$', read.Topic.as_view(), name='topic'),  # public
]

yolla/topic/urls.py
from django.urls import path, re_path
from . import views as v

app_name = 'topic'

urlpatterns = [
    path('list', v.List.as_view(), name='list'),  # superuser only
    path('new', v.New.as_view(), name='new'),  # superuser only
    re_path(r'^update/(?P<pk>\d+)$', v.Update.as_view(), name='update'),  # superuser only

    re_path(r'^(?P<category_slug>[\w-]+)$', v.Category.as_view(), name='category'),  # public
]

yolla/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.urls import include, re_path
from yolla.common import error_handlers


urlpatterns = [
    re_path(r'^', include('yolla.common.urls')),
    re_path(r'^participants/', include('yolla.participant.urls')),
    re_path(r'^categories/', include('yolla.category.urls', namespace='category')),
    re_path(r'^topics/', include('yolla.topic.urls', namespace='topic')),
    re_path(r'^opinions/', include('yolla.opinion.urls', namespace='opinion')),
    re_path(r'^articles/', include('yolla.article.urls', namespace='article')),
    re_path(r'^jumbotrons/', include('yolla.jumbotron.urls', namespace='jumbotron')),
]

handler403 = error_handlers.status_code_403
handler404 = error_handlers.status_code_404

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forumcorona/opinion/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from forumcorona.participant.models import Participant
from forumcorona.topic.models import Topic


opinion_statuses = (
    (1, '1. Published'),
    (2, '2. Preparing to publish'),
    (3, '3. Accepted'),
    (4, '4. Posted by publisher'),
    (5, '5. Draft'),
    (6, '6. Rejected'),
    (7, '7. Deleted by publisher'),
)
opinion_statuses_to_display_to_participant = (
    (1, _('Published')),
    (2, _('Preparing to publish')),
    (3, _('Accepted by moderator')),
    (4, _('Sent for publication')),
    (6, _('Rejected by moderator')),
    (7, _('Canceled to publish')),
)


def opinion_verbose_status(status_num, to_display_to_participant=False):
    if to_display_to_participant is False:
        for status in opinion_statuses:
            if status[0] == status_num:
                return status[1]
    for status in opinion_statuses_to_display_to_participant:
        if status[0] == status_num:
            return status[1]


class Opinion(models.Model):
    class Meta:
        db_table = 'opinion'
        ordering = ('pk',)

    recorded = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    status = models.PositiveSmallIntegerField(db_index=True, default=4, choices=opinion_statuses)
    reason_for_rejection = models.TextField(blank=True)

    publisher = models.ForeignKey(Participant, models.PROTECT)
    topic = models.ForeignKey(Topic, models.PROTECT)

    apex = models.ForeignKey('self', models.PROTECT, null=True)
    apex_language = models.CharField(max_length=20)

    en_text = models.TextField('Text in English', blank=True)
    zh_hans_text = models.TextField('Text in Chinese', blank=True)
    es_text = models.TextField('Text in Spanish', blank=True)
    ar_text = models.TextField('Text in Arabic', blank=True)
    fr_text = models.TextField('Text in French', blank=True)
    ru_text = models.TextField('Text in Russian', blank=True)


class OpinionAttachment(models.Model):
    class Meta:
        db_table = 'opinion_attachment'

    opinion = models.ForeignKey(Opinion, models.PROTECT)
    document = models.FileField(upload_to='%Y-%m-%d/')
    original_label = models.CharField(max_length=200, default='')
    md5 = models.CharField(db_index=True, max_length=32, default='')
    size = models.PositiveIntegerField(default=0)
    deleted = models.BooleanField(default=False)

yolla/opinion/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from . import models as m


class ReplyEditForm(forms.ModelForm):
    class Meta:
        model = m.Opinion
        fields = ('en_text', 'zh_hans_text', 'es_text', 'ar_text', 'fr_text', 'ru_text')
        labels = {
            'en_text': _('Reply in English'),
            'zh_hans_text': _('Reply in Chinese'),
            'es_text': _('Reply in Spanish'),
            'ar_text': _('Reply in Arabic'),
            'fr_text': _('Reply in French'),
            'ru_text': _('Reply in Russian'),
        }

forumcorona/opinion/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import F
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import ListView, CreateView, UpdateView
from forumcorona.common import mixins as mix
from forumcorona.common.utils import login_and_staff_required
from . import models as m


class FilterByTopicAndStatusMixin:
    topic_id = None
    status_id = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['topic_id'] = self.topic_id
        context['status_id'] = self.status_id

        context['topic_verbose'] = 'Filter by topic'
        context['status_verbose'] = 'Filter by status'
        context['apply_btn'] = 'Apply filters'
        context['reset_btn'] = 'Reset'
        return context

    def get_queryset(self):
        qs = super().get_queryset()

        topic = self.request.GET.get('topic')
        try:
            qs = qs.filter(topic=int(topic))
            self.topic_id = int(topic)
        except (TypeError, ValueError):
            pass
        status = self.request.GET.get('status')
        try:
            qs = qs.filter(status=int(status))
            self.status_id = int(status)
        except (TypeError, ValueError):
            pass
        return qs


class List(LoginRequiredMixin, mix.StaffRequiredMixin, mix.ListViewContextPaginated, FilterByTopicAndStatusMixin, ListView):
    model = m.Opinion
    template_name = 'opinion/list.html'
    # topics_categories = {
    #     'Subcategory 1 of first category': {
    #         1: '1-1-1 topic',
    #         2: '1-1-2 topic',
    #     },
    #     'Subcategory 2 of first category': {
    #         3: '1-2-1 topic',
    #         4: '1-2-2 topic',
    #     },
    # }
    topics_categories = {}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['label'] = 'Opinions'
        context['topics_categories'] = self.topics_categories
        context['statuses'] = m.opinion_statuses
        return context

    def get_queryset(self):
        qs = super().get_queryset().order_by('-updated')

        # QuerySet
        opinions_values = qs.values('id', 'recorded', 'updated', 'status', 'topic_id', 'en_text', publisher_name=F('publisher_id__name'))
        topics_values = m.Topic.objects.all().values('id', 'en_name', category_en_name=F('category_id__en_name'))

        # Making object_list & self.topics_categories
        topics_en_name = {}
        for topic in topics_values:
            topics_en_name[topic['id']] = topic['en_name']
            self.topics_categories[topic['category_en_name']] = {}
        for topic in topics_values:
            self.topics_categories[topic['category_en_name']][topic['id']] = topic['en_name']

        opinions = []
        for opinion in opinions_values:
            opinions.append({
                'id': opinion['id'],
                'recorded': opinion['recorded'],
                'updated': opinion['updated'],
                'verbose_status': m.opinion_verbose_status(opinion['status']),
                'publisher_name': opinion['publisher_name'],
                'topic_id': opinion['topic_id'],
                'topic_en_name': topics_en_name[opinion['topic_id']],
                'en_text': opinion['en_text'],
            })
        return opinions


class New(LoginRequiredMixin, mix.SuperUserRequiredMixin, mix.MsgInFormValid, CreateView):
    model = m.Opinion
    fields = ('status',
              'en_text', 'zh_hans_text', 'es_text', 'ar_text', 'fr_text', 'ru_text')
    template_name = 'opinion/form.html'
    success_message = 'New opinion: done.'
    topic_values = None

    def dispatch(self, request, *args, **kwargs):
        self.topic_values = get_object_or_404(
            m.Topic.objects.values(
                'id', 'slug', 'en_name', category_apex_en_name=F('category_id__apex_id__en_name'), category_en_name=F('category_id__en_name')
            ),
            slug=kwargs.get('topic_slug')
        )
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'label': 'New opinion',
            'topic': self.topic_values,
        })
        if m.Opinion.objects.filter(topic_id=self.topic_values['id']).count() > 0:
            messages.warning(self.request, 'This topic already have apex opinion.')
        return context

    def form_valid(self, form):
        form.instance.publisher = self.request.user
        form.instance.topic_id = self.topic_values['id']
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('opinion:read', kwargs={'pk': self.object.id})


class Update(LoginRequiredMixin, mix.StaffRequiredMixin, mix.MsgInFormValid, UpdateView):
    model = m.Opinion
    fields = ('status', 'reason_for_rejection',
              'en_text', 'zh_hans_text', 'es_text', 'ar_text', 'fr_text', 'ru_text')
    template_name = 'opinion/form.html'
    success_url = reverse_lazy('opinion:list')
    success_message = 'Opinion updated.'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        topic_values = get_object_or_404(
            m.Topic.objects.values(
                'id', 'slug', 'en_name', category_apex_en_name=F('category_id__apex_id__en_name'), category_en_name=F('category_id__en_name')
            ),
            pk=self.object.topic_id
        )
        context.update({
            'label': 'Update opinion',
            'topic': topic_values,
            'opinion_id': self.kwargs.get('pk'),
            'documents': m.OpinionAttachment.objects.filter(opinion_id=self.object.pk,
                                                            deleted=False).values('id', 'document', 'original_label', 'size'),
        })
        return context

    def form_valid(self, form):
        if form.cleaned_data.get('status') == 6 and not form.cleaned_data.get('reason_for_rejection'):
            messages.error(self.request, '"Reason for rejection" must be filled in.')
            return super().form_invalid(form)
        if form.cleaned_data.get('status') == 1:
            form.instance.topic.updated = timezone.now()
            form.instance.topic.save(update_fields=('updated',))
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('opinion:read', kwargs={'pk': self.kwargs.get('pk')})


@login_and_staff_required
def read(request, pk):
    opinion_values = get_object_or_404(
        m.Opinion.objects.values(
            'recorded', 'updated', 'status', 'reason_for_rejection',
            'en_text', 'zh_hans_text', 'es_text', 'ar_text', 'fr_text', 'ru_text',
            publisher_name=F('publisher_id__name'),
            topic_category_apex_en_name=F('topic_id__category_id__apex_id__en_name'),
            topic_category_en_name=F('topic_id__category_id__en_name'),
            topic_en_name=F('topic_id__en_name'),
            apex_recorded=F('apex_id__recorded'),
            apex_publisher_name=F('apex_id__publisher_id__name'),
            apex_en_text=F('apex_id__en_text'),
        ),
        pk=pk
    )
    return render(request, 'opinion/read.html', {
        'label': 'Read opinion',
        'opinion_id': pk,
        'opinion': opinion_values,
        'opinion_verbose_status': m.opinion_verbose_status(opinion_values['status']),
        'documents': m.OpinionAttachment.objects.filter(opinion_id=pk, deleted=False).values('id', 'document', 'original_label', 'size'),
    })

forumcorona/topic/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import F
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView
from forumcorona.common import mixins as mix
from forumcorona.common.utils import lang
from forumcorona.article.models import get_article_for_context
from forumcorona.jumbotron.models import get_jumbotron_for_context
from . import models as m


class List(LoginRequiredMixin, mix.SuperUserRequiredMixin, mix.ListViewContextPaginated, ListView):
    model = m.Topic
    template_name = 'topic/list.html'
    category_id = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['label'] = 'Topics'
        context['filter_by_category'] = self.category_id
        return context

    def get_queryset(self):
        qs = super().get_queryset()
        category = self.request.GET.get('category')
        try:
            if category:
                qs = qs.filter(category=int(category))
                self.category_id = int(category)
        except ValueError:
            pass
        return qs.values('id', 'created', 'updated', 'slug', 'published', 'en_name', category_en_name=F('category_id__en_name'),)


class New(LoginRequiredMixin, mix.SuperUserRequiredMixin, mix.MsgInFormValid, CreateView):
    model = m.Topic
    fields = ('slug', 'published', 'category',
              'en_name', 'zh_hans_name', 'es_name', 'ar_name', 'fr_name', 'ru_name',
              'en_description', 'zh_hans_description', 'es_description', 'ar_description', 'fr_description', 'ru_description')
    template_name = 'topic/form.html'
    success_url = reverse_lazy('topic:list')
    success_message = 'New topic: done.'
    extra_context = {
        'label': 'New topic',
    }


class Update(LoginRequiredMixin, mix.SuperUserRequiredMixin, mix.MsgInFormValid, UpdateView):
    model = m.Topic
    fields = ('slug', 'published', 'category',
              'en_name', 'zh_hans_name', 'es_name', 'ar_name', 'fr_name', 'ru_name',
              'en_description', 'zh_hans_description', 'es_description', 'ar_description', 'fr_description', 'ru_description')
    template_name = 'topic/form.html'
    success_url = reverse_lazy('topic:list')
    success_message = 'Topic updated.'
    extra_context = {
        'label': 'Update topic',
    }


class Category(mix.ListViewContextPaginated, ListView):
    model = m.Topic
    template_name = 'topic/category.html'
    category_values = None

    def dispatch(self, request, *args, **kwargs):
        self.category_values = get_object_or_404(
            m.Category.objects.values('id', apex_slug=F('apex_id__slug'), apex_name=F('apex_id__'+lang('_name')), name=F(lang('_name')),),
            slug=kwargs.get('category_slug')
        )
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'label': self.category_values['name'],
            'category': self.category_values,
            'article': get_article_for_context(self.request.user, self.request.META['HTTP_USER_AGENT'],
                                               category_id_only=self.category_values['id']),
            'jumbotron': get_jumbotron_for_context(self.request.user, category_id_only=self.category_values['id']),
        })
        return context

    def get_queryset(self):
        qs = super().get_queryset().filter(category_id=self.category_values['id'], published=True)
        return qs.values('slug', name=F(lang('_name')), description=F(lang('_description')),)

templates/opinion/cancel.html
{% extends "base.html" %}
{% block content %}
{% load i18n %}
<div class="breadcrumbs">
	<a href="{% url 'opinion:replies' %}"><bdi>{% trans 'Your replies' %}</bdi></a> / <bdi>{{ opinion.topic_category_apex_name }}</bdi> / <bdi>{{ opinion.topic_category_name }}</bdi> / <bdi>{{ opinion.topic_name }}</bdi>
</div>
<div class="panel">
	<div class="panel-header"><bdi>{{ opinion.publisher_name }}</bdi><small>{{ opinion.recorded }}</small></div>
	<div class="panel-body">
		<blockquote class="text-muted">
			<span>{% trans 'Reply to' %}: <bdi>{{ opinion.apex_publisher_name }}</bdi><small>({{ opinion.apex_recorded }})</small></span>
			{{ opinion.apex_text|linebreaks }}
		</blockquote>
		{{ opinion.text|linebreaks }}
	</div>
</div>
<h4>{% trans 'Are you sure you want to cancel the publication of your reply?' %}</h4>
<p class="text-muted">{% trans 'Even after cancellation, you can read your reply' %}</p>
<form method="post">
	{% csrf_token %}
	<button type="submit" class="btn primary">{% trans 'Yes' %}</button>
	<button onclick="window.history.back();" class="btn">{% trans 'Go back' %}</button>
</form>
{% endblock %}

templates/opinion/replies.html
{% extends "base.html" %}
{% block content %}
{% load i18n %}
{% include 'common/if_messages.html' %}
{% include 'opinion/filter_topic_status.html' %}
<table class="tbl bordered">
	<thead>
		<tr>
			<th class="text-center">{% trans "Recorded" %}</th>
			<th class="text-center">{% trans "Status" %}</th>
			<th class="text-center">{% trans "Topic name" %}</th>
			<th class="text-center">{% trans "Text" %} ({% trans "symbols" %} <=200)</th>
			<th class="text-center" width="135px">{% trans "Actions" %}</th>
		</tr>
	</thead>
	<tbody>
		{% for element in object_list %}
			<tr>
				<td class="text-center">{{ element.recorded }}</td>
				<td class="text-center">{{ element.verbose_status }}</td>
				<td class="text-center">{{ element.topic_name }}</td>
				<td>{{ element.text|truncatechars:200 }}</td>
				<td class="text-center">
					<a href="{% url 'opinion:your_reply' pk=element.id %}">{% trans "Read your reply" %}</a><br>
					{% if element.status == 4 %}
						<a href="{% url 'opinion:edit' pk=element.id %}">{% trans "Edit" %}</a><br>
						<a href="{% url 'opinion:attach_documents' opinion_pk=element.id %}">{% trans "Documents" %}</a><br>
						<a href="{% url 'opinion:cancel' pk=element.id %}">{% trans "Cancel" %}</a>
					{% endif %}
				</td>
			</tr>
		{% endfor %}
	</tbody>
</table>
{% include 'common/pagination.html' %}
{% endblock %}

templates/opinion/reply.html
{% extends "base.html" %}
{% block content %}
{% load i18n %}
{% include 'common/if_messages.html' %}
{% include 'common/if_form.errors.html' %}
<div class="breadcrumbs">
	<a href="{% url 'category:container' slug=opinion.topic_category_apex_slug %}"><bdi>{{ opinion.topic_category_apex_name }}</bdi></a> / <a href="{% url 'topic:category' category_slug=opinion.topic_category_slug %}"><bdi>{{ opinion.topic_category_name }}</bdi></a> / <a href="{% url 'opinion:topic' topic_slug=opinion.topic_slug %}"><bdi>{{ opinion.topic_name }}</bdi></a> / <bdi>{{ label }}</bdi>
</div>
{% if previous_reply %}
	<div class="alert info">
		<div class="alert-title clearfix">
			<i class="alert-icon alert-tri-white text-info"></i>
			<span>{% trans 'You have already replied' %}</span>
		</div>
		{% trans 'Status' %}: {{ previous_reply_verbose_status }}
	</div>
{% endif %}
<div class="panel">
	<div class="panel-header"><bdi>{{ previous_reply.0.publisher_name|default:'' }}</bdi><small>{{ previous_reply.0.recorded|default:'' }}</small></div>
	<div class="panel-body">
		<blockquote class="text-muted">
			<span>{% trans 'Reply to' %}: <bdi>{{ opinion.publisher_name }}</bdi><small>({{ opinion.recorded }})</small></span>
			{{ opinion.text|linebreaks }}
		</blockquote>
		{{ previous_reply.0.text|default:''|linebreaks }}
	</div>
</div>
{% if not previous_reply %}
	{% include 'opinion/reply_edit_form.html' %}
{% endif %}
{% endblock %}

templates/opinion/topic.html
{% extends "base.html" %}
{% block content %}
{% load i18n %}
{% load language_dir readable_file_size from utils %}
<div class="breadcrumbs">
	<a href="{% url 'category:container' slug=topic.category_apex_slug %}"><bdi>{{ topic.category_apex_name }}</bdi></a> / <a href="{% url 'topic:category' category_slug=topic.category_slug %}"><bdi>{{ topic.category_name }}</bdi></a> / <bdi>{{ topic.name }}</bdi>
</div>
{% if l2 %}
	{% for element in object_list %}
		<div class="panel">
			<div class="panel-header"><bdi>{{ element.publisher_name }}</bdi><small>{{ element.recorded }}</small>
				<div class="panel-btn-area clearfix">
					<a href="{% url 'opinion:reply' reply_to_opinion_pk=element.id %}" class="btn primary glow">{% trans "Reply" %}</a>
				</div>
			</div>
			<div class="panel-body">
				{% if element.apex_recorded %}
					<blockquote class="text-muted">
						<span>{% trans 'Reply to' %}: <bdi>{{ element.apex_publisher_name }}</bdi><small>({{ element.apex_recorded }})</small></span>
						{{ element.apex_text|linebreaks }}
					</blockquote>
				{% endif %}
				{{ element.l1_text|linebreaks }}<div class="line"></div>
				<div class="text-success" dir="{{ l2|language_dir }}" lang="{{ l2 }}">{{ element.l2_text|linebreaks }}</div>
				{% if element.documents %}
					<div class="line"></div>
					<p><b>{% trans "Documents" %}</b> (<a href="{% url 'opinion:zip_documents' opinion_pk=element.id %}" target="_blank">{% trans "Download documents in ZIP-archive" %}</a>)</p>
					<ul>
					{% for document in element.documents %}
						<li><a href="{{ MEDIA_URL }}{{ document.document }}" target="_blank" dir="auto">{{ document.original_label }}</a> [<bdi>{{ document.size|readable_file_size }}</bdi>]</li>
					{% endfor %}
					</ul>
				{% endif %}
			</div>
		</div>
	{% endfor %}
{% else %}
	{% for element in object_list %}
		<div class="panel" itemscope itemtype="https://schema.org/Comment">
			<div class="panel-header"><bdi>{{ element.publisher_name }}</bdi><small>{{ element.recorded }}</small>
				<div class="panel-btn-area clearfix">
					<a href="{% url 'opinion:reply' reply_to_opinion_pk=element.id %}" class="btn primary glow">{% trans "Reply" %}</a>
				</div>
			</div>
			<div class="panel-body">
				{% if element.apex_recorded %}
					<blockquote class="text-muted">
						<span>{% trans 'Reply to' %}: <bdi>{{ element.apex_publisher_name }}</bdi><small>({{ element.apex_recorded }})</small></span>
						{{ element.apex_text|linebreaks }}
					</blockquote>
				{% endif %}
				<div itemprop="text">{{ element.l1_text|linebreaks }}</div>
				{% if element.documents %}
					<div class="line"></div>
					<p><b>{% trans "Documents" %}</b> (<a href="{% url 'opinion:zip_documents' opinion_pk=element.id %}" target="_blank">{% trans "Download documents in ZIP-archive" %}</a>)</p>
					<ul>
					{% for document in element.documents %}
						<li><a href="{{ MEDIA_URL }}{{ document.document }}" target="_blank" dir="auto">{{ document.original_label }}</a> [<bdi>{{ document.size|readable_file_size }}</bdi>]</li>
					{% endfor %}
					</ul>
				{% endif %}
			</div>
		</div>
	{% endfor %}
{% endif %}
{% include 'common/pagination.html' %}
{% endblock %}

templates/opinion/your_reply.html
{% extends "base.html" %}
{% block content %}
{% load i18n %}
{% load language_dir readable_file_size from utils %}
{% include 'common/if_messages.html' %}
<div class="breadcrumbs">
	<a href="{% url 'opinion:replies' %}"><bdi>{% trans 'Your replies' %}</bdi></a> / <bdi>{{ opinion.topic_category_apex_name }}</bdi> / <bdi>{{ opinion.topic_category_name }}</bdi> / <bdi>{{ opinion.topic_name }}</bdi>
</div>
<div class="alert info">
	<div class="alert-title clearfix">
		<i class="alert-icon alert-tri-white text-info"></i>
		<span>{% trans 'Status' %}: {{ opinion_verbose_status }}</span>
	</div>
	{% if opinion.status == 6 %}<b>{% trans 'Reason for rejection' %}</b><br>{{ opinion.reason_for_rejection }}{% endif %}
</div>
<div class="panel">
	<div class="panel-header"><bdi>{{ opinion.publisher_name }}</bdi><small>{{ opinion.recorded }}</small></div>
	<div class="panel-body">
		{% if opinion.apex_recorded %}
			<blockquote class="text-muted">
				<span>{% trans 'Reply to' %}: <bdi>{{ opinion.apex_publisher_name }}</bdi> <small>({{ opinion.apex_recorded }})</small></span>
				{{ opinion.apex_text|linebreaks }}
			</blockquote>
		{% endif %}
		{{ opinion.l1_text|linebreaks }}
		{% if l2 %}
			<div class="line"></div>
			<div class="text-success" dir="{{ l2|language_dir }}" lang="{{ l2 }}">{{ opinion.l2_text|linebreaks }}</div>
		{% endif %}
		{% if documents %}
			<div class="line"></div>
			<p><b>{% trans "Documents" %}</b> (<a href="{% url 'opinion:zip_documents' opinion_pk=opinion_id %}" target="_blank">{% trans "Download documents in ZIP-archive" %}</a>)</p>
			<ul>
			{% for document in documents %}
				<li><a href="{{ MEDIA_URL }}{{ document.document }}" target="_blank" dir="auto">{{ document.original_label }}</a> [<bdi>{{ document.size|readable_file_size }}</bdi>]</li>
			{% endfor %}
			</ul>
		{% endif %}
	</div>
</div>
{% if opinion.status == 4 or opinion.status == 5 %}
	<a href="{% url 'opinion:attach_documents' opinion_pk=opinion_id %}" class="btn btn-ghost rounded-more-corners">{% trans "Documents" %}</a>
{% endif %}
{% endblock %}