yolla/article/urls.py
from django.urls import path, re_path
from . import views as v, views_media as media

app_name = 'article'

urlpatterns = [
    path('list', v.List.as_view(), name='list'),  # superuser only
    path('new', v.New.as_view(), name='new'),  # superuser only
    re_path(r'^update/(?P<pk>\d+)$', v.Update.as_view(), name='update'),  # superuser only
    re_path(r'^read/(?P<pk>\d+)$', v.read, name='read'),  # superuser only

    re_path(r'^upload_images$', media.upload_images, name='upload_images'),  # superuser only
    re_path(r'^delete_image/(?P<media_pk>\d+)$', media.delete_image, name='delete_image'),  # superuser only
]

yolla/category/urls.py
from django.urls import path, re_path
from . import views as v

app_name = 'category'

urlpatterns = [
    path('list', v.List.as_view(), name='list'),  # superuser only
    path('new', v.New.as_view(), name='new'),  # superuser only
    re_path(r'^update/(?P<pk>\d+)$', v.Update.as_view(), name='update'),  # superuser only

    re_path(r'^(?P<slug>[\w-]+)$', v.container, name='container'),  # public
]

yolla/common/urls.py
from django.urls import path
from . import views as v

app_name = 'common'

urlpatterns = [
    path('', v.categories_with_topics, name='page_home'),
]

yolla/opinion/urls.py
from django.urls import path, re_path
from . import views as v, views_reply as reply, views_attachment as attachment, views_read as read

app_name = 'opinion'

urlpatterns = [
    path('list', v.List.as_view(), name='list'),  # staff
    re_path(r'^new/(?P<topic_slug>[\w-]+)$', v.New.as_view(), name='new'),  # superuser only
    re_path(r'^update/(?P<pk>\d+)$', v.Update.as_view(), name='update'),  # staff
    re_path(r'^read/(?P<pk>\d+)$', v.read, name='read'),  # staff

    re_path(r'^reply_to_(?P<reply_to_opinion_pk>\d+)$', reply.Reply.as_view(), name='reply'),  # participant
    re_path(r'^edit_(?P<pk>\d+)$', reply.Edit.as_view(), name='edit'),  # participant
    re_path(r'^cancel_(?P<pk>\d+)$', reply.cancel, name='cancel'),  # participant

    re_path(r'^attach_documents_(?P<opinion_pk>\d+)$', attachment.attach_documents, name='attach_documents'),  # participant
    re_path(r'^delete_document_(?P<attachment_pk>\d+)$', attachment.delete_document, name='delete_document'),  # participant
    re_path(r'^documents_(?P<opinion_pk>\d+)$', attachment.zip_documents, name='zip_documents'),  # public

    path('replies', read.Replies.as_view(), name='replies'),  # participant
    re_path(r'^your_reply_(?P<pk>\d+)$', read.your_reply, name='your_reply'),  # participant
    re_path(r'^(?P<topic_slug>[\w-]+)$', read.Topic.as_view(), name='topic'),  # public
]

yolla/topic/urls.py
from django.urls import path, re_path
from . import views as v

app_name = 'topic'

urlpatterns = [
    path('list', v.List.as_view(), name='list'),  # superuser only
    path('new', v.New.as_view(), name='new'),  # superuser only
    re_path(r'^update/(?P<pk>\d+)$', v.Update.as_view(), name='update'),  # superuser only

    re_path(r'^(?P<category_slug>[\w-]+)$', v.Category.as_view(), name='category'),  # public
]

yolla/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.urls import include, re_path
from yolla.common import error_handlers


urlpatterns = [
    re_path(r'^', include('yolla.common.urls')),
    re_path(r'^participants/', include('yolla.participant.urls')),
    re_path(r'^categories/', include('yolla.category.urls', namespace='category')),
    re_path(r'^topics/', include('yolla.topic.urls', namespace='topic')),
    re_path(r'^opinions/', include('yolla.opinion.urls', namespace='opinion')),
    re_path(r'^articles/', include('yolla.article.urls', namespace='article')),
    re_path(r'^jumbotrons/', include('yolla.jumbotron.urls', namespace='jumbotron')),
]

handler403 = error_handlers.status_code_403
handler404 = error_handlers.status_code_404

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forumcorona/common/views.py
from django.shortcuts import render
from django.utils.translation import ugettext_lazy as _
from forumcorona.common.utils import lang
from forumcorona.category.models import Category
from forumcorona.topic.models import get_topics_grouped_by_category_id
from forumcorona.article.models import get_article_for_context
from forumcorona.jumbotron.models import get_jumbotron_for_context


def categories_with_topics(request):
    categories_values = Category.objects.all().values('id', 'slug', 'apex', lang('_name'))
    # categories_topics = {
    #     1: ('First category', {
    #         3: ('Subcategory 1 of first category', [
    #             'Topic 1 of subcategory 1 of first category',
    #             'Topic 2 of subcategory 1 of first category',
    #             'Topic 3 of subcategory 1 of first category',
    #         ]),
    #         4: ('Subcategory 2 of first category', [...]),
    #     }),
    #     2: ('Second category', {...}),
    # }
    categories_topics = {}
    if categories_values:
        the_categories = {}
        categories_pre_tree = {}
        for category in categories_values:
            the_categories[category['id']] = {
                'id': category['id'],
                'slug': category['slug'],
                'apex': category['apex'],
                'name': category[lang('_name')],
            }
            categories_pre_tree[category['apex']] = {}
        for key, item in the_categories.items():
            categories_pre_tree[item['apex']][item['id']] = item

        categories_of_topics = []
        for key1, item1 in categories_pre_tree[None].items():
            try:
                for key2, item2 in categories_pre_tree[key1].items():
                    categories_of_topics.append(key2)
            except KeyError:
                pass  # (key1, item1): categories with apex=None

        topics = get_topics_grouped_by_category_id(categories_of_topics)

        for key1, item1 in categories_pre_tree[None].items():
            subcategory = {}
            try:
                for key2, item2 in categories_pre_tree[key1].items():
                    subcategory[key2] = (item2, topics[key2])
            except KeyError:
                pass  # (key1, item1): categories with apex=None
            categories_topics[key1] = (item1, subcategory)
    return render(request, 'common/page_home.html', {
        'label': 'Forumcorona.net',
        'h1': _('Important discussions'),
        'categories_topics': categories_topics,
        'page_home': True,
        'article': get_article_for_context(request.user, request.META['HTTP_USER_AGENT']),
        'jumbotron': get_jumbotron_for_context(request.user),
        'more_topics': _('more topics'),
    })

yolla/common/views.py
from django.shortcuts import render
from django.utils.translation import ugettext_lazy as _
from yolla.common.utils import lang
from yolla.category.models import Category
from yolla.topic.models import get_topics_grouped_by_category_id
from yolla.article.models import get_article_for_context
from yolla.jumbotron.models import get_jumbotron_for_context


def categories_with_topics(request):
    categories_values = Category.objects.all().values('id', 'slug', 'apex', lang('_name'))
    # categories_topics = {
    #     1: ('First category', {
    #         3: ('Subcategory 1 of first category', [
    #             'Topic 1 of subcategory 1 of first category',
    #             'Topic 2 of subcategory 1 of first category',
    #             'Topic 3 of subcategory 1 of first category',
    #         ]),
    #         4: ('Subcategory 2 of first category', [...]),
    #     }),
    #     2: ('Second category', {...}),
    # }
    categories_topics = {}
    if categories_values:
        the_categories = {}
        categories_pre_tree = {}
        for category in categories_values:
            the_categories[category['id']] = {
                'id': category['id'],
                'slug': category['slug'],
                'apex': category['apex'],
                'name': category[lang('_name')],
            }
            categories_pre_tree[category['apex']] = {}
        for key, item in the_categories.items():
            categories_pre_tree[item['apex']][item['id']] = item

        categories_of_topics = []
        for key1, item1 in categories_pre_tree[None].items():
            try:
                for key2, item2 in categories_pre_tree[key1].items():
                    categories_of_topics.append(key2)
            except KeyError:
                pass  # (key1, item1): categories with apex=None

        topics = get_topics_grouped_by_category_id(categories_of_topics)

        for key1, item1 in categories_pre_tree[None].items():
            subcategory = {}
            try:
                for key2, item2 in categories_pre_tree[key1].items():
                    subcategory[key2] = (item2, topics[key2])
            except KeyError:
                pass  # (key1, item1): categories with apex=None
            categories_topics[key1] = (item1, subcategory)
    return render(request, 'common/page_home.html', {
        'label': 'Yolla',
        'h1': _('Important discussions'),
        'categories_topics': categories_topics,
        'page_home': True,
        'article': get_article_for_context(request.user, request.META['HTTP_USER_AGENT']),
        'jumbotron': get_jumbotron_for_context(request.user),
        'more_topics': _('more topics'),
    })

templates/common/error_handlers.html
{% extends "base.html" %}
{% block content %}<h2 class="text-secondary">{{ content }}</h2>{% endblock %}

templates/common/form_article_jumbotron.html
{% extends "base.html" %}
{% block content %}
{% load select_category_in_other_apps_form from category %}{% select_category_in_other_apps_form as categories_dict %}
{% load substr_in_str language_dir_form_field from utils %}
{% include 'common/if_messages.html' %}
{% include 'common/if_form.errors.html' %}
<form method="post">
	{% csrf_token %}
	{% for field in form %}
		<div class="form-elements">
			{% if field.auto_id == 'id_mobile' or field.auto_id == 'id_page_home' %}
				<label class="form-check-radio toggle-check">
					{{ field }}
					<span class="toggle-check-box"></span>
					<span class="toggle-check-text">{{ field.label }}</span>
				</label>
			{% elif field.auto_id == 'id_category' %}
				{{ field.label_tag }}
				<select name="category" id="id_category">
					<option value="">---------</option>
					{% for key1, item1 in categories_dict.items %}
						<option value="{{ item1.0.id }}"{% if object.category_id == item1.0.id %} selected{% endif %}>{{ item1.0.name }}</option>
						{% for key2, item2 in item1.1.items %}
							<option value="{{ item2.0.id }}"{% if object.category_id == item2.0.id %} selected{% endif %}>- {{ item2.0.name }}</option>
						{% endfor %}
					{% endfor %}
				</select>
			{% elif field.auto_id == 'id_topic' %}
				{{ field.label_tag }}
				<select name="topic" id="id_topic">
					<option value="">---------</option>
					{% for key1, item1 in topics_categories.items %}
						<option disabled>{{ key1 }}</option>
						{% for key2, item2 in item1.items %}
							<option value="{{ key2 }}"{% if object.topic_id == key2 %} selected{% endif %}>- {{ item2 }}</option>
						{% endfor %}
					{% endfor %}
				</select>
			{% elif field.name|substr_in_str:'_content' is True %}
				{{ field.label_tag }}
				{{ field|language_dir_form_field:'_content' }}
			{% else %}
				{{ field.label_tag }}
				{{ field }}
			{% endif %}
		</div>
	{% endfor %}
	<button type="submit" class="btn primary">Save</button>
</form>
{% endblock %}

templates/common/if_form.errors.html
{% if form.errors %}
{% load i18n %}
<div class="alert secondary">
	<div class="alert-title clearfix">
		<i class="alert-icon alert-tri-white text-secondary"></i>
		<span>{% if form.errors.items|length == 1 %}{% trans 'Please correct the error below.' %}{% else %}{% trans 'Please correct the errors below.' %}{% endif %}</span>
	</div>
	<ul>
		{% for field in form %}
			{% if field.errors %}
				<li><a href="#{{ field.auto_id }}" class="text-white"><b>{{ field.label }}</b></a>
					<ul>
						{% for error in field.errors %}
							<li>{{ error|escape }}</li>
						{% endfor %}
					</ul>
				</li>
			{% endif %}
		{% endfor %}
	</ul>
	{% if form.non_field_errors %}
		{{ form.non_field_errors }}
	{% endif %}
</div>
{% endif %}

templates/common/if_messages.html
{% if messages %}
{% for msg in messages %}
<div class="alert {% if msg.tags == 'success' %}success{% elif msg.tags == 'error' %}danger{% elif msg.tags == 'info' %}info{% elif msg.tags == 'warning' %}warning{% endif %}">
	<div class="alert-title clearfix">
		<i class="alert-icon alert-tri-white text-{% if msg.tags == 'success' %}success{% elif msg.tags == 'error' %}danger{% elif msg.tags == 'info' %}info{% elif msg.tags == 'warning' %}warning{% endif %}"></i>
		<span>{{ msg }}</span>
	</div>
</div>
{% endfor %}
{% endif %}

templates/common/page_home.html
{% extends "base.html" %}
{% block content %}
{% for key1, item1 in categories_topics.items %}
	<div class="home-h2"><a href="{% url 'category:container' slug=item1.0.slug %}" class="text-secondary">{{ item1.0.name }}</a></div>
	{% for key2, item2 in item1.1.items %}
		<div class="home-h3"><a href="{% url 'topic:category' category_slug=item2.0.slug %}" class="text-danger">{{ item2.0.name }}</a></div>
		{% for item3 in item2.1 %}
			<div class="home-h4"><a href="{% url 'opinion:topic' topic_slug=item3.slug %}" class="text-primary">{{ item3.name }}</a></div>
		{% endfor %}
		<div class="home-h4"><a href="{% url 'topic:category' category_slug=item2.0.slug %}" class="text-primary">{{ more_topics }}...</a></div>
	{% endfor %}
{% endfor %}
{% endblock %}

templates/common/pagination.html
{% if is_paginated %}
{% if paginator.page_range|length <= 21 %}
	<ul class="paging">
		<li><a {% if not page_obj.has_previous %}class="disabled"{% endif %} {% if page_obj.has_previous %}href="?page={{ page_obj.previous_page_number }}&paginate_by={{ paginate_by }}"{% else %}tabindex="-1"{% endif %}>«</a></li>
		{% for page in paginator.page_range %}
			<li><a {% if page == page_obj.number %}class="active primary"{% endif %} href="?page={{ page }}&paginate_by={{ paginate_by }}">{{ page }}</a></li>
		{% endfor %}
		<li><a {% if not page_obj.has_next %}class="disabled"{% endif %} {% if page_obj.has_next %}href="?page={{ page_obj.next_page_number }}&paginate_by={{ paginate_by }}"{% else %}tabindex="-1"{% endif %}>»</a></li>
	</ul>
{% else %}
	{% load i18n %}
	<div class="flex-grid">
		<div class="col-3 col-4-sm">
			<a class="btn btn-sm rounded-more-corners{% if not page_obj.has_previous %} disabled{% endif %}" {% if page_obj.has_previous %}href="?page={{ page_obj.previous_page_number }}&paginate_by={{ paginate_by }}"{% else %}tabindex="-1"{% endif %}>« {% trans 'Previous' %}</a>
		</div>
		<div class="col-6 col-4-sm text-center">
			<form>
				<select class="paging-select" name="page" onchange="this.form.submit();" required>
					{% for page in paginator.page_range %}
						<option value="{{ page }}"{% if page == page_obj.number %} selected{% endif %}>{% trans 'Page' %} {{ page }}</option>
					{% endfor %}
				</select>
				<input type="hidden" name="paginate_by" value="{{ paginate_by }}">
			</form>
		</div>
		<div class="col-3 col-4-sm text-right">
			<a class="btn btn-sm rounded-more-corners{% if not page_obj.has_next %} disabled{% endif %}" {% if page_obj.has_next %}href="?page={{ page_obj.next_page_number }}&paginate_by={{ paginate_by }}"{% else %}tabindex="-1"{% endif %}>{% trans 'Next' %} »</a>
		</div>
	</div>
{% endif %}
{% endif %}

templates/common/topbar.html
{% load static %}
{% load i18n %}
{% load categories_for_top_nav from category %}{% categories_for_top_nav as categories_dict %}
<header class="main-container header fixed">
	{# <!-- Nav Bar with Logo Area --> #}
	<div class="flex-grid navbar">
		{# <!-- Mobile Menu --> #}
		<input type="checkbox" id="mobileMenu" class="hide">
		<label id="mobileMenuLabel" class="mobile-menu left-side" for="mobileMenu">
			<i class="hamburger"></i>
		</label>
		<label class="full-screen" for="mobileMenu"></label>
		{# <!-- /Mobile Menu --> #}

		<div class="col-2 col-12-md logo clearfix">
			<a href="/">
				<span>Yolla</span>
				<img src="{% static 'img/yolla.png' %}" title="yolla">
			</a>
		</div>

		<nav class="col-8 col-12-md navbarright" id="topMenuNav">
			<div class="navbar-links">
				{% for key1, item1 in categories_dict.items %}
					<div class="has-drop-menu hover-menu">{{ item1.0.name }} <i class="arrow-down"></i>
						<ul class="drop-menu">
							{% for key2, item2 in item1.1.items %}
								<li><a href="{% url 'topic:category' category_slug=item2.0.slug %}">{{ item2.0.name }}</a></li>
							{% endfor %}
						</ul>
					</div>
				{% endfor %}
			</div>
		</nav>
		{# <!-- Second menu --> #}
		{# <!-- Second Mobile Menu --> #}
		<input type="checkbox" id="mobileMenu2" class="hide">
		<label id="mobileMenuLabel2" class="mobile-menu right-side" for="mobileMenu2">
			<i class="profile"></i>
		</label>
		<label class="full-screen" for="mobileMenu2"></label>
		{# <!-- /Second Mobile Menu --> #}
		<nav class="col-2 col-12-md text-right" id="topMenuNav2">
			<div class="navbar-links">
				<div class="has-drop-menu hover-menu">
					{% if user.is_authenticated is False %}{% trans 'Log in' %}{% else %}{% trans 'Profile' %}{% endif %} <i class="arrow-down"></i>
					<ul class="drop-menu drop-menu-left">
						{% if user.is_authenticated is False %}
							<li><a href="{% url 'participant:login' %}">{% trans 'Log in' %}</a></li>
							<li><a href="{% url 'participant:signup' %}">{% trans 'Sign up' %}</a></li>
						{% else %}
							<li><a href="{% url 'opinion:replies' %}">{% trans 'Your replies' %}</a></li>
							<li class="line"></li>
							<li><a href="{% url 'participant:password' %}">{% trans 'Change password' %}</a></li>
							<li><a href="{% url 'participant:profile' %}">{% trans 'Profile' %}</a></li>
							<li><a href="{% url 'participant:logout' %}">{% trans 'Log out' %}</a></li>
							{% if user.is_staff is True %}
								<li class="line"></li>
								<li><a href="{% url 'opinion:list' %}?status=4">Opinions</a></li>
							{% endif %}
							{% if user.is_superuser is True %}
								<li class="line"></li>
								<li>
									<a href="{% url 'jumbotron:list' %}">Jumbotrons</a>
									<a href="{% url 'jumbotron:new' %}">New jumbotron</a>
								</li>
								<li>
									<a href="{% url 'article:list' %}">Articles</a>
									<a href="{% url 'article:new' %}">New article</a>
								</li>
								<li>
									<a href="{% url 'article:upload_images' %}">Upload images to articles</a>
								</li>
								<li class="line"></li>
								<li>
									<a href="{% url 'topic:list' %}">Topics</a>
									<a href="{% url 'topic:new' %}">New topic</a>
								</li>
								<li>
									<a href="{% url 'category:list' %}">Categories</a>
									<a href="{% url 'category:new' %}">New category</a>
								</li>
							{% endif %}
						{% endif %}
					</ul>
				</div>
				<div class="has-drop-menu hover-menu">{% trans 'Theme' %} <i class="arrow-down"></i>
					<ul class="drop-menu drop-menu-left">
						<li><a href="javascript:;" onclick="changeTheme('dark');" class="dark-theme-link"><span></span> {% trans 'Dark' %}</a></li>
						<li><a href="javascript:;" onclick="changeTheme('classic');" class="classic-theme-link"><span></span> {% trans 'Classic' %}</a></li>
					</ul>
				</div>
			</div>
		</nav>
		{# <!-- /Second menu --> #}
	</div>
</header>