yolla/opinion/urls.py
from django.urls import path, re_path
from . import views as v, views_reply as reply, views_attachment as attachment, views_read as read

app_name = 'opinion'

urlpatterns = [
    path('list', v.List.as_view(), name='list'),  # staff
    re_path(r'^new/(?P<topic_slug>[\w-]+)$', v.New.as_view(), name='new'),  # superuser only
    re_path(r'^update/(?P<pk>\d+)$', v.Update.as_view(), name='update'),  # staff
    re_path(r'^read/(?P<pk>\d+)$', v.read, name='read'),  # staff

    re_path(r'^reply_to_(?P<reply_to_opinion_pk>\d+)$', reply.Reply.as_view(), name='reply'),  # participant
    re_path(r'^edit_(?P<pk>\d+)$', reply.Edit.as_view(), name='edit'),  # participant
    re_path(r'^cancel_(?P<pk>\d+)$', reply.cancel, name='cancel'),  # participant

    re_path(r'^attach_documents_(?P<opinion_pk>\d+)$', attachment.attach_documents, name='attach_documents'),  # participant
    re_path(r'^delete_document_(?P<attachment_pk>\d+)$', attachment.delete_document, name='delete_document'),  # participant
    re_path(r'^documents_(?P<opinion_pk>\d+)$', attachment.zip_documents, name='zip_documents'),  # public

    path('replies', read.Replies.as_view(), name='replies'),  # participant
    re_path(r'^your_reply_(?P<pk>\d+)$', read.your_reply, name='your_reply'),  # participant
    re_path(r'^(?P<topic_slug>[\w-]+)$', read.Topic.as_view(), name='topic'),  # public
]

yolla/participant/urls.py
from django.urls import path
from . import views as v

app_name = 'participant'

urlpatterns = [
    path('signup', v.signup, name='signup'),  # public
    path('password', v.password, name='password'),  # participant
    path('profile', v.profile, name='profile'),  # participant

    path('login', v.LoginView.as_view(), name='login'),  # public
    path('logout', v.LogoutView.as_view(), name='logout'),  # public
    path('password_reset', v.PasswordResetView.as_view(), name='password_reset'),  # public
    path('password_reset/done', v.PasswordResetDoneView.as_view(), name='password_reset_done'),  # public
    path('reset/<uidb64>/<token>', v.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),  # public
    path('reset/done', v.PasswordResetCompleteView.as_view(), name='password_reset_complete'),  # public
]

yolla/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.urls import include, re_path
from yolla.common import error_handlers


urlpatterns = [
    re_path(r'^', include('yolla.common.urls')),
    re_path(r'^participants/', include('yolla.participant.urls')),
    re_path(r'^categories/', include('yolla.category.urls', namespace='category')),
    re_path(r'^topics/', include('yolla.topic.urls', namespace='topic')),
    re_path(r'^opinions/', include('yolla.opinion.urls', namespace='opinion')),
    re_path(r'^articles/', include('yolla.article.urls', namespace='article')),
    re_path(r'^jumbotrons/', include('yolla.jumbotron.urls', namespace='jumbotron')),
]

handler403 = error_handlers.status_code_403
handler404 = error_handlers.status_code_404

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% spaceless %}
{% load static %}
{% load i18n %}
{% load language_dir from utils %}
{% if user.is_authenticated is False %}{% load languages_settings language_in_url from utils %}{% languages_settings as languages %}{% endif %}
<html dir="{{ request.LANGUAGE_CODE|language_dir }}" lang="{{ request.LANGUAGE_CODE }}">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="content-type" content="text/html; charset=UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, user-scalable=no">
	<title>{{ label }}</title>
	<link rel="stylesheet" href="{% static 'purecssframework.css' %}">
	<link rel="stylesheet" href="{% static 'theme-dark.css' %}">
	<link rel="stylesheet" href="{% static 'purecssframework-site.css' %}">
	<link rel="stylesheet" href="{% static 'css.css' %}">
	<link rel="stylesheet" href="{% static 'custom.css' %}">
	{% if user.is_authenticated is True and user.is_staff is True %}
		<link rel="stylesheet" href="{% static 'admin.css' %}">
	{% endif %}
	<link rel="shortcut icon" href="/favicon.ico">
</head>
<body class="{{ request.COOKIES.theme|default:'' }}" id="body">
{% include 'common/topbar.html' %}
<div class="fixed-nav-space" id="top"></div>
{% if jumbotron.l1_content %}
	<div class="hero-area">
		<div class="main-container">
			<div class="flex-grid ">
				<div class="col-12">
					{% if jumbotron.l2_content %}
						<div dir="{{ article.l1_dir }}" lang="{{ article.l1_code }}">{{ jumbotron.l1_content|safe }}</div>
						<div dir="{{ article.l2_dir }}" lang="{{ article.l2_code }}">{{ jumbotron.l2_content|safe }}</div>
					{% else %}
						{{ jumbotron.l1_content|safe }}
					{% endif %}
				</div>
			</div>
		</div>
	</div>
{% endif %}
<div class="main-container">
	<div class="flex-grid">
		{% if article.l1_content and 'mobile' in request.META.HTTP_USER_AGENT|lower %}{% include 'article/article_content.html' %}{% endif %}
		<div class="col-{% if article.l1_content %}7{% else %}12{% endif %}">
			<h1 class="text-center">{{ h1|default:label }}</h1>
			{% block content %}{% endblock %}
		</div>
		{% if article.l1_content and 'mobile' not in request.META.HTTP_USER_AGENT|lower %}{% include 'article/article_content.html' %}{% endif %}
	</div>
</div>
<footer class="text-center">
	<div class="line"></div>
	{% if user.is_authenticated is False %}
	{% else %}
		<a href="{% url 'opinion:replies' %}">{% trans 'Your replies' %}</a>
		<a href="{% url 'participant:password' %}">{% trans 'Change password' %}</a>
		<a href="{% url 'participant:profile' %}">{% trans 'Profile' %}</a>
		<a href="{% url 'participant:logout' %}">{% trans 'Log out' %}</a>
	{% endif %}
	<br>{% now "Y" %}<a href="https://github.com/yulaymusin/yolla" target="_blank">Yolla</a>
</footer>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
{% if user.is_authenticated is True %}
	{% if '/participants/profile' in request.get_full_path or '/categories/new' in request.get_full_path or '/categories/update' in request.get_full_path or '/topics/new' in request.get_full_path or '/topics/update' in request.get_full_path or '/topics/list' in request.get_full_path or '/opinions/list' in request.get_full_path or '/opinions/replies' in request.get_full_path or '/articles/new' in request.get_full_path or '/articles/update' in request.get_full_path or '/jumbotrons/new' in request.get_full_path or '/jumbotrons/update' in request.get_full_path %}
		<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet">
		<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
		<script>
			$(document).ready(function() {
				var select2_dir = "{{ request.LANGUAGE_CODE|language_dir }}";
				$( 'select' ).select2({ dir: select2_dir });  // opinion/list
			});
			$(document).on('select2:open', () => { document.querySelector('.select2-search__field').focus(); });
		</script>
	{% endif %}
{% endif %}
<script src="{% static 'custom.js' %}"></script>
{% if user.is_authenticated is True and user.is_staff is True %}
	<script src="{% static 'admin.js' %}"></script>
{% endif %}
</body>
</html>
{% endspaceless %}