yolla/article/urls.py
from django.urls import path, re_path
from . import views as v, views_media as media

app_name = 'article'

urlpatterns = [
    path('list', v.List.as_view(), name='list'),  # superuser only
    path('new', v.New.as_view(), name='new'),  # superuser only
    re_path(r'^update/(?P<pk>\d+)$', v.Update.as_view(), name='update'),  # superuser only
    re_path(r'^read/(?P<pk>\d+)$', v.read, name='read'),  # superuser only

    re_path(r'^upload_images$', media.upload_images, name='upload_images'),  # superuser only
    re_path(r'^delete_image/(?P<media_pk>\d+)$', media.delete_image, name='delete_image'),  # superuser only
]

yolla/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.urls import include, re_path
from yolla.common import error_handlers


urlpatterns = [
    re_path(r'^', include('yolla.common.urls')),
    re_path(r'^participants/', include('yolla.participant.urls')),
    re_path(r'^categories/', include('yolla.category.urls', namespace='category')),
    re_path(r'^topics/', include('yolla.topic.urls', namespace='topic')),
    re_path(r'^opinions/', include('yolla.opinion.urls', namespace='opinion')),
    re_path(r'^articles/', include('yolla.article.urls', namespace='article')),
    re_path(r'^jumbotrons/', include('yolla.jumbotron.urls', namespace='jumbotron')),
]

handler403 = error_handlers.status_code_403
handler404 = error_handlers.status_code_404

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forumcorona/article/models.py
from django.conf import settings
from django.db import models
from django.db.models import F
from forumcorona.common.utils import lang
from forumcorona.category.models import Category
from forumcorona.topic.models import Topic

article_statuses = (
    (1, '1. Published'),
    (2, '2. Preparing to publish'),
    (3, '3. Draft'),
)


def article_verbose_status(status_num):
    for status in article_statuses:
        if status[0] == status_num:
            return status[1]


class Article(models.Model):
    class Meta:
        db_table = 'article'
        ordering = ('mobile', 'status', '-page_home', 'category', 'topic', 'pk',)

    mobile = models.BooleanField(default=False)
    status = models.PositiveSmallIntegerField(default=3, choices=article_statuses)

    page_home = models.BooleanField(default=False)
    category = models.ForeignKey(Category, models.PROTECT, null=True, blank=True)
    topic = models.ForeignKey(Topic, models.PROTECT, null=True, blank=True)

    en_content = models.TextField('Content in English', blank=True)
    zh_hans_content = models.TextField('Content in Chinese', blank=True)
    es_content = models.TextField('Content in Spanish', blank=True)
    ar_content = models.TextField('Content in Arabic', blank=True)
    fr_content = models.TextField('Content in French', blank=True)
    ru_content = models.TextField('Content in Russian', blank=True)


class ArticleMedia(models.Model):
    class Meta:
        db_table = 'article_media'
        ordering = ('image',)

    image = models.FileField(upload_to='')
    md5 = models.CharField(max_length=32, default='')
    size = models.PositiveIntegerField(default=0)


def media_url_in_str(article_content):
    return article_content.replace('[MEDIA_URL]', settings.MEDIA_URL)


def get_article_for_context(user, http_user_agent, category_id_only=None, topic_id_only=None):
    if user.is_authenticated and user.l2:
        a = Article.objects.values(l1=F(lang('_content')), l2=F(user.l2.replace('-', '_') + '_content'),)
    else:
        a = Article.objects.values_list(lang('_content'), flat=True)

    if 'mobile' in http_user_agent.lower():
        a = a.filter(mobile=True)

    if not category_id_only and not topic_id_only:
        a = a.filter(status=1, page_home=True)[:1]
    elif category_id_only and not topic_id_only:
        a = a.filter(status=1, category_id=category_id_only)[:1]
    elif not category_id_only and topic_id_only:
        a = a.filter(status=1, topic_id=topic_id_only)[:1]
    else:
        a = None

    if a and user.is_authenticated and user.l2:
        article = {
            'l1_content': media_url_in_str(a[0]['l1']),
            'l2_content': media_url_in_str(a[0]['l2']),
        }
        for language in settings.LANGUAGES:
            if language[0] == user.l1:
                article.update({'l1_name': language[1], 'l1_code': language[0],
                                'l1_dir': 'rtl' if language[0] in settings.RTL_LANGUAGES_CODES else 'ltr'})
            if language[0] == user.l2:
                article.update({'l2_name': language[1], 'l2_code': language[0],
                                'l2_dir': 'rtl' if language[0] in settings.RTL_LANGUAGES_CODES else 'ltr'})
        return article
    elif a:
        return {'l1_content': media_url_in_str(a[0])}

    return None

yolla/article/models.py
from django.conf import settings
from django.db import models
from django.db.models import F
from yolla.common.utils import lang
from yolla.category.models import Category
from yolla.topic.models import Topic

article_statuses = (
    (1, '1. Published'),
    (2, '2. Preparing to publish'),
    (3, '3. Draft'),
)


def article_verbose_status(status_num):
    for status in article_statuses:
        if status[0] == status_num:
            return status[1]


class Article(models.Model):
    class Meta:
        db_table = 'article'
        ordering = ('mobile', 'status', '-page_home', 'category', 'topic', 'pk',)

    mobile = models.BooleanField(default=False)
    status = models.PositiveSmallIntegerField(default=3, choices=article_statuses)

    page_home = models.BooleanField(default=False)
    category = models.ForeignKey(Category, models.PROTECT, null=True, blank=True)
    topic = models.ForeignKey(Topic, models.PROTECT, null=True, blank=True)

    en_content = models.TextField('Content in English', blank=True)
    zh_hans_content = models.TextField('Content in Chinese', blank=True)
    es_content = models.TextField('Content in Spanish', blank=True)
    ar_content = models.TextField('Content in Arabic', blank=True)
    fr_content = models.TextField('Content in French', blank=True)
    ru_content = models.TextField('Content in Russian', blank=True)


class ArticleMedia(models.Model):
    class Meta:
        db_table = 'article_media'
        ordering = ('image',)

    image = models.FileField(upload_to='')
    md5 = models.CharField(max_length=32, default='')
    size = models.PositiveIntegerField(default=0)


def media_url_in_str(article_content):
    return article_content.replace('[MEDIA_URL]', settings.MEDIA_URL)


def get_article_for_context(user, http_user_agent, category_id_only=None, topic_id_only=None):
    if user.is_authenticated and user.l2:
        a = Article.objects.values(l1=F(lang('_content')), l2=F(user.l2.replace('-', '_') + '_content'),)
    else:
        a = Article.objects.values_list(lang('_content'), flat=True)

    if 'mobile' in http_user_agent.lower():
        a = a.filter(mobile=True)

    if not category_id_only and not topic_id_only:
        a = a.filter(status=1, page_home=True)[:1]
    elif category_id_only and not topic_id_only:
        a = a.filter(status=1, category_id=category_id_only)[:1]
    elif not category_id_only and topic_id_only:
        a = a.filter(status=1, topic_id=topic_id_only)[:1]
    else:
        a = None

    if a and user.is_authenticated and user.l2:
        article = {
            'l1_content': media_url_in_str(a[0]['l1']),
            'l2_content': media_url_in_str(a[0]['l2']),
        }
        for language in settings.LANGUAGES:
            if language[0] == user.l1:
                article.update({'l1_name': language[1], 'l1_code': language[0],
                                'l1_dir': 'rtl' if language[0] in settings.RTL_LANGUAGES_CODES else 'ltr'})
            if language[0] == user.l2:
                article.update({'l2_name': language[1], 'l2_code': language[0],
                                'l2_dir': 'rtl' if language[0] in settings.RTL_LANGUAGES_CODES else 'ltr'})
        return article
    elif a:
        return {'l1_content': media_url_in_str(a[0])}

    return None

forumcorona/article/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import F
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView
from forumcorona.common import mixins as mix
from forumcorona.common.utils import login_and_superuser_required
from . import models as m


class List(LoginRequiredMixin, mix.SuperUserRequiredMixin, mix.ListViewContextPaginated, ListView):
    model = m.Article
    template_name = 'article/list.html'
    extra_context = {
        'label': 'Articles',
    }

    def get_queryset(self):
        qs = super().get_queryset()
        articles_values = qs.values('id', 'mobile', 'status', 'page_home', 'en_content', category_en_name=F('category_id__en_name'),
                                    topic_en_name=F('topic_id__en_name'),)
        articles = []
        for article in articles_values:
            articles.append({
                'id': article['id'],
                'mobile': article['mobile'],
                'verbose_status': m.article_verbose_status(article['status']),
                'page_home': article['page_home'],
                'category_en_name': article['category_en_name'],
                'topic_en_name': article['topic_en_name'],
                'en_content': article['en_content'],
            })
        return articles


class New(LoginRequiredMixin, mix.SuperUserRequiredMixin, mix.MsgInFormValid, mix.TopicsCategoriesContext, CreateView):
    model = m.Article
    fields = ('mobile', 'status', 'page_home', 'category', 'topic',
              'en_content', 'zh_hans_content', 'es_content', 'ar_content', 'fr_content', 'ru_content')
    template_name = 'common/form_article_jumbotron.html'
    success_message = 'New article: done.'
    extra_context = {
        'label': 'New article',
    }

    def get_success_url(self):
        return reverse_lazy('article:read', kwargs={'pk': self.object.id})


class Update(LoginRequiredMixin, mix.SuperUserRequiredMixin, mix.MsgInFormValid, mix.TopicsCategoriesContext, UpdateView):
    model = m.Article
    fields = ('mobile', 'status', 'page_home', 'category', 'topic',
              'en_content', 'zh_hans_content', 'es_content', 'ar_content', 'fr_content', 'ru_content')
    template_name = 'common/form_article_jumbotron.html'
    success_message = 'Article updated.'
    extra_context = {
        'label': 'Update article',
    }

    def get_success_url(self):
        return reverse_lazy('article:read', kwargs={'pk': self.kwargs.get('pk')})


@login_and_superuser_required
def read(request, pk):
    article_values = get_object_or_404(
        m.Article.objects.values(
            'mobile', 'status', 'page_home',
            'en_content', 'zh_hans_content', 'es_content', 'ar_content', 'fr_content', 'ru_content',
            category_en_name=F('category_id__en_name'), topic_en_name=F('topic_id__en_name'),
        ),
        pk=pk
    )
    return render(request, 'article/read.html', {
        'label': 'Read article',
        'article_id': pk,
        'article': {
            'page_home': article_values['page_home'],
            'category_en_name': article_values['category_en_name'],
            'topic_en_name': article_values['topic_en_name'],

            'en_content': m.media_url_in_str(article_values['en_content']),
            'zh_hans_content': m.media_url_in_str(article_values['zh_hans_content']),
            'es_content': m.media_url_in_str(article_values['es_content']),
            'ar_content': m.media_url_in_str(article_values['ar_content']),
            'fr_content': m.media_url_in_str(article_values['fr_content']),
            'ru_content': m.media_url_in_str(article_values['ru_content']),
        },
        'article_verbose_status': m.article_verbose_status(article_values['status']),
    })

yolla/article/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import F
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView
from yolla.common import mixins as mix
from yolla.common.utils import login_and_superuser_required
from . import models as m


class List(LoginRequiredMixin, mix.SuperUserRequiredMixin, mix.ListViewContextPaginated, ListView):
    model = m.Article
    template_name = 'article/list.html'
    extra_context = {
        'label': 'Articles',
    }

    def get_queryset(self):
        qs = super().get_queryset()
        articles_values = qs.values('id', 'mobile', 'status', 'page_home', 'en_content', category_en_name=F('category_id__en_name'),
                                    topic_en_name=F('topic_id__en_name'),)
        articles = []
        for article in articles_values:
            articles.append({
                'id': article['id'],
                'mobile': article['mobile'],
                'verbose_status': m.article_verbose_status(article['status']),
                'page_home': article['page_home'],
                'category_en_name': article['category_en_name'],
                'topic_en_name': article['topic_en_name'],
                'en_content': article['en_content'],
            })
        return articles


class New(LoginRequiredMixin, mix.SuperUserRequiredMixin, mix.MsgInFormValid, mix.TopicsCategoriesContext, CreateView):
    model = m.Article
    fields = ('mobile', 'status', 'page_home', 'category', 'topic',
              'en_content', 'zh_hans_content', 'es_content', 'ar_content', 'fr_content', 'ru_content')
    template_name = 'common/form_article_jumbotron.html'
    success_message = 'New article: done.'
    extra_context = {
        'label': 'New article',
    }

    def get_success_url(self):
        return reverse_lazy('article:read', kwargs={'pk': self.object.id})


class Update(LoginRequiredMixin, mix.SuperUserRequiredMixin, mix.MsgInFormValid, mix.TopicsCategoriesContext, UpdateView):
    model = m.Article
    fields = ('mobile', 'status', 'page_home', 'category', 'topic',
              'en_content', 'zh_hans_content', 'es_content', 'ar_content', 'fr_content', 'ru_content')
    template_name = 'common/form_article_jumbotron.html'
    success_message = 'Article updated.'
    extra_context = {
        'label': 'Update article',
    }

    def get_success_url(self):
        return reverse_lazy('article:read', kwargs={'pk': self.kwargs.get('pk')})


@login_and_superuser_required
def read(request, pk):
    article_values = get_object_or_404(
        m.Article.objects.values(
            'mobile', 'status', 'page_home',
            'en_content', 'zh_hans_content', 'es_content', 'ar_content', 'fr_content', 'ru_content',
            category_en_name=F('category_id__en_name'), topic_en_name=F('topic_id__en_name'),
        ),
        pk=pk
    )
    return render(request, 'article/read.html', {
        'label': 'Read article',
        'article_id': pk,
        'article': {
            'mobile': article_values['mobile'],
            'page_home': article_values['page_home'],
            'category_en_name': article_values['category_en_name'],
            'topic_en_name': article_values['topic_en_name'],

            'en_content': m.media_url_in_str(article_values['en_content']),
            'zh_hans_content': m.media_url_in_str(article_values['zh_hans_content']),
            'es_content': m.media_url_in_str(article_values['es_content']),
            'ar_content': m.media_url_in_str(article_values['ar_content']),
            'fr_content': m.media_url_in_str(article_values['fr_content']),
            'ru_content': m.media_url_in_str(article_values['ru_content']),
        },
        'article_verbose_status': m.article_verbose_status(article_values['status']),
    })

templates/article/article_content.html
<div class="col-5 call-out primary">
	{% if article.l2_content %}
		<div class="tab-elements line-tabs">
			<input type="radio" id="line-tab-1" name="line-tabs-elements" checked>
			<input type="radio" id="line-tab-2" name="line-tabs-elements">
			<div class="responsive-tabs">
				<div class="tab-btns">
					<label for="line-tab-1" class="btn" dir="{{ article.l1_dir }}" lang="{{ article.l1_code }}">{{ article.l1_name }}</label>
					<label for="line-tab-2" class="btn" dir="{{ article.l2_dir }}" lang="{{ article.l2_code }}">{{ article.l2_name }}</label>
				</div>
			</div>
			<div class="tab-info-wrap">
				<div class="tab-info" dir="{{ article.l1_dir }}" lang="{{ article.l1_code }}">{{ article.l1_content|safe }}</div>
				<div class="tab-info" dir="{{ article.l2_dir }}" lang="{{ article.l2_code }}">{{ article.l2_content|safe }}</div>
			</div>
		</div>
	{% else %}
		<div itemprop="articleBody" itemscope itemtype="https://schema.org/Article">{{ article.l1_content|safe }}</div>
	{% endif %}
</div>

templates/article/delete_image.html
{% extends "base.html" %}
{% block content %}
{% load readable_file_size from utils %}
<h4>Are you sure you want to permanently delete this image from the server storage?</h4>
<h5><a href="{{ MEDIA_URL }}{{ image.image }}" target="_blank">{{ image.label }}</a> [{{ image.size|readable_file_size }}]</h5>
<form method="post">
	{% csrf_token %}
	<input type="submit" class="btn primary" value="Delete">
	<a href="{% url 'article:upload_images' %}{% if request.GET.table == '1' %}?list=1{% endif %}" class="btn">Go back</a>
</form>
{% endblock %}

templates/article/list.html
{% extends "base.html" %}
{% block content %}
{% include 'common/if_messages.html' %}
<table class="tbl bordered">
	<thead>
		<tr>
			<th class="text-center">ID</th>
			<th class="text-center">Mobile</th>
			<th class="text-center">Status</th>
			<th class="text-center">Show in page home</th>
			<th class="text-center">Category name in English</th>
			<th class="text-center">Topic name in English</th>
			<th class="text-center">Content in English [:100]</th>
			<th class="text-center">Actions</th>
		</tr>
	</thead>
	<tbody>
		{% for element in object_list %}
			<tr>
				<td class="text-center">{{ element.id }}</td>
				<td class="text-center">{% if element.mobile is True %}&#10004;{% else %}&#10008;{% endif %} {{ element.mobile }}</td>
				<td class="text-center">{{ element.verbose_status }}</td>
				<td class="text-center">{% if element.page_home is True %}&#10004;{% else %}&#10008;{% endif %} {{ element.page_home }}</td>
				<td>{{ element.category_en_name|default:'' }}</td>
				<td>{{ element.topic_en_name|default:'' }}</td>
				<td>{{ element.en_content|truncatechars:100 }}</td>
				<td class="text-center">
					<a href="{% url 'article:update' pk=element.id %}">Update</a><br>
					<a href="{% url 'article:read' pk=element.id %}">Read</a>
				</td>
			</tr>
		{% endfor %}
	</tbody>
</table>
{% include 'common/pagination.html' %}
{% endblock %}

templates/article/read.html
{% extends "base.html" %}
{% block content %}
{% include 'common/if_messages.html' %}
<div class="alert info">
	<div class="alert-title clearfix">
		<i class="alert-icon alert-tri-white text-info"></i>
		<span>Status: {{ article_verbose_status }}</span>
	</div>
	Mobile: <b>{% if article.mobile is True %}&#10004;{% else %}&#10008;{% endif %}</b><br>
	Show in page home: <b>{% if article.page_home is True %}&#10004;{% else %}&#10008;{% endif %}</b><br>
	Category name in English: <b>{{ article.category_en_name|default:'&#10008;' }}</b><br>
	Topic name in English: <b>{{ article.topic_en_name|default:'&#10008;' }}</b><br>
	<a href="{% url 'article:update' pk=article_id %}">Update this article</a>
</div>

<h3>Content in English</h3>
<div class="call-out info" dir="ltr" lang="en">{{ article.en_content|safe }}</div>
<h3>Content in Chinese</h3>
<div class="call-out info" dir="ltr" lang="zh-hans">{{ article.zh_hans_content|safe }}</div>
<h3>Content in Spanish</h3>
<div class="call-out info" dir="ltr" lang="es">{{ article.es_content|safe }}</div>
<h3>Content in Arabic</h3>
<div class="call-out info" dir="rtl" lang="ar">{{ article.ar_content|safe }}</div>
<h3>Content in French</h3>
<div class="call-out info" dir="ltr" lang="fr">{{ article.fr_content|safe }}</div>
<h3>Content in Russian</h3>
<div class="call-out info" dir="ltr" lang="ru">{{ article.ru_content|safe }}</div>

<a href="{% url 'article:update' pk=article_id %}" class="btn info">Update this article</a>
{% endblock %}

templates/article/upload_images.html
{% extends "base.html" %}
{% block content %}
{% load readable_file_size from utils %}
{% include 'common/if_messages.html' %}
<div class="breadcrumbs">
	<a href="{% url 'article:list' %}">Articles</a> / Upload images
</div>
<div id="images">
	{% if request.GET.list != '1' %}
		<a href="?list=1" class="btn btn-xs" style="float: right;">Show images as a list</a>
		<h4>Images</h4>
		<table class="tbl bordered">
			<thead>
				<tr>
					<th class="text-center">Actions</th>
					<th class="text-center">Image file name</th>
					<th class="text-center">Image</th>
					<th class="text-center">Image file size</th>
					<th class="text-center">Image HTML tag</th>
				</tr>
			</thead>
			<tbody>
			{% for image in images %}
				<tr>
					<td class="text-center">
						<a onclick="copyImageHTMLTagToClipboard('{{ image.id }}');" class="tooltip tip-right">
							Copy image tag<span class="tip" id="copy_img_tip_{{ image.id }}">Copy image HTML tag to clipboard</span>
						</a><br>
						<a href="{% url 'article:delete_image' media_pk=image.id %}">Delete</a>
					</td>
					<td><a href="{{ MEDIA_URL }}{{ image.image }}" target="_blank">{{ image.label }}</a></td>
					<td class="text-center"><a href="{{ MEDIA_URL }}{{ image.image }}" target="_blank"><img src="{{ MEDIA_URL }}{{ image.image }}"></a></td>
					<td class="text-center">{{ image.size|readable_file_size }}</td>
					<td><input id="image_html_tag_{{ image.id }}" value="&lt;img src=&quot;[MEDIA_URL]{{ image.image }}&quot;&gt;"></td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
	{% else %}
		<a href="?" class="btn btn-xs" style="float: right;">Show images as a table</a>
		<h4>Images</h4>
		<ul>
		{% for image in images %}
			<li><a href="{{ MEDIA_URL }}{{ image.image }}" target="_blank">{{ image.label }}</a> [{{ image.size|readable_file_size }}] (<a href="{% url 'article:delete_image' media_pk=image.id %}?list=1">Delete</a>)</li>
		{% endfor %}
		</ul>
	{% endif %}
</div>

<h3>Upload images</h3>
<div id="csrf_token" value="{{ csrf_token }}"></div>
<div class="form-elements">
	<input type="file" id="upload_images" accept="{% for fn_ext in allowed_filename_extensions %}.{{ fn_ext }},{% endfor %}" multiple>
</div>
<div id="images_list"></div>
<div class="loading-bar" id="loading_bar"><div class="bar" style="width: 0%"></div></div>
<div class="alert danger text-white" id="upload_images_error" f_max_size="{{ file_max_size }}">
	<div class="alert-title clearfix">
		<i class="alert-icon alert-tri-white text-danger"></i>
		<span>Requirements for uploading images</span>
	</div>
The size of each file should not exceed {{ file_max_size|readable_file_size }}.<br>
Only supported types of files.
</div>
<button id="upload_btn" class="btn primary">Upload</button>
{% endblock %}